// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzmRGs5063PnKyleFpXLt5tnXMSY6R4i4',
    appId: '1:162122062181:web:8cf0ea3302fd75c867a98c',
    messagingSenderId: '162122062181',
    projectId: 'dhtstore-87485',
    authDomain: 'dhtstore-87485.firebaseapp.com',
    storageBucket: 'dhtstore-87485.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFd8jIe1w2hEqATxDzDsAYFTwIfigyz-4',
    appId: '1:162122062181:android:10bf494ae8bf7f3967a98c',
    messagingSenderId: '162122062181',
    projectId: 'dhtstore-87485',
    storageBucket: 'dhtstore-87485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVLJ7hKbKlPpaj7mBc1YnuQECXNFl-9G8',
    appId: '1:162122062181:ios:3ced541869bff2bd67a98c',
    messagingSenderId: '162122062181',
    projectId: 'dhtstore-87485',
    storageBucket: 'dhtstore-87485.appspot.com',
    iosBundleId: 'com.example.cuoiky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVLJ7hKbKlPpaj7mBc1YnuQECXNFl-9G8',
    appId: '1:162122062181:ios:e809bb7ba5dd9c0767a98c',
    messagingSenderId: '162122062181',
    projectId: 'dhtstore-87485',
    storageBucket: 'dhtstore-87485.appspot.com',
    iosBundleId: 'com.example.cuoiky.RunnerTests',
  );
}
